### ISSUE TITLE
Is it ready to use it now in WooCommerce?

### ISSUE THREAD

**Issue by ihelpco** [paytabscom/paytabs-woocommerce#1]
Hi @wajihkm and @paytabscom, how are you doing?
I have a WooCommerce Store using the old PayTabs plugin, and we face some problems.
Can we use this updated version?
If not, when do you expect the final release?
Thanks

**Comment by wajihkm** [comment]
Hi @ihelpco ,
Thanks for asking, We hope you are doing well.
The last release published now and it is ready to use.

[https://github.com/paytabscom/paytabs-woocommerce/releases/tag/3.1.0](url)

Regards
