### ISSUE TITLE
Payment API callback URL for IPN

### ISSUE THREAD

**Issue by ihelpco** [paytabscom/paytabs-woocommerce#13]
Hi @wajihkm and @samymassoud,
I need you help to get the correct IPN URL of my website so that I can fill in the IPN URL in my paytabs account:
![paytabs-screen](https://user-images.githubusercontent.com/62771226/115383611-b9fb5500-a1de-11eb-9501-373a2afdbb60.png)

All my clients complain that the customers paid but the order status is still pending in WooCommerce.

For example:
Checkout.com has a WooCommerce plugin and the IPN url is:
https://example.com/?wc-api=wc_checkoutcom_webhook
I tried it and it is working great. I made a refund on Checkout.com dashboard and the order status on my website is changed to Refunded Automatically.

Thanks

**Comment by wajihkm** [comment]
Hi @ihelpco 

Sorry for the inconvenience you had.

IPN is not yet supported in our WooCommerce plugin.
We have queue this task and will work on it soon.

Thanks

**Comment by ihelpco** [comment]
Hello @wajihkm,
Thanks for you answer. I hope you add it as soon as possible because it is a TOP priority.
I see most of your clients are complaining about this issue and they don't know about this feature.

Thanks

**Comment by wajihkm** [comment]
Hi @ihelpco 
Thanks for your feedback.
To be more clear: Our current plugin works as expected.
It changes the Order status after the payment completes.
The IPN feature will add more communications between PayTabs dashboard & the WooCommerce system (ex: refund from the dashboard will change the Order status on the Woo system)

If you are facing some issues, please share the following details:
- WordPress version
- Theme
- PayTabs plugin version

You can send them to out customer care team.

Thanks
