### ISSUE TITLE
'state' post variable not found

### ISSUE THREAD

**Issue by ihelpco** [paytabscom/paytabs-woocommerce#2]
Hi @paytabscom and @wajihkm,
I want to report a bug in your old and new WooCommerce plugin.
When I choose Kuwait, Bahrain or UAE in checkout page, the state field is hidden in Woocommerce because these countries don't use states in their address.
The problem is that your plugin shows this error ( 'state' post variable not found ).
Please don't make the state field required.
A lot of my customers from these countries failed to pay via PayTabs because of this error.
Please make it a high priority.
Thanks.

**Comment by wajihkm** [comment]
Hi @ihelpco ,
Thanks for your report.
We have fixed this issue.
