### ISSUE TITLE
Translation template .pot

### ISSUE THREAD

**Issue by ihelpco** [paytabscom/paytabs-woocommerce#3]
Hello @wajihkm,
I tried this new release, it is working great.
But I suggest that you include a Translation template (.pot file) that contains all the strings that can be translated.
Our store is in Arabic, so we need to translate all the confirmation messages from your plugin.
Most of our customers don't know that the payment is successful because they can't read your confirmation messages.

Sorry for sending more requests, but I am a PayTabs Affiliate and I have a lot of customers working with you.
Thanks

**Comment by wajihkm** [comment]
Hi @ihelpco ,
We are happy to hear that from you.

We will consider adding Arabic translation strings into the next release.

Can you clarify the next point, please
> Most of our customers don't know that the payment is successful because they can't read your confirmation messages

Nothing to be sorry about, We are happy to get supportive feedback and help you.

Thanks & Regards

**Comment by ihelpco** [comment]
Hi @wajihkm, thanks for your support.
I meant that the customers receive a confirmation message in English but they don't understand it.
All we need is to translate these messages to Arabic.
Thanks
