### ISSUE TITLE
Missing Wordpress plugin Header: GitHub Plugin URI

### ISSUE THREAD

**Issue by fabricelaborie** [paytabscom/paytabs-woocommerce#34]
As per  Wordpress guidelines,
https://developer.wordpress.org/plugins/plugin-basics/header-requirements/
"the main PHP file should include header comment that tells WordPress that a file is a plugin and provides information about the plugin."
I see many are already included.
It would be  great to include one additional header:
` * GitHub Plugin URI: https://github.com/paytabscom/paytabs-woocommerce`
this would allow the plugin Git Updater ( [https://git-updater.com/git-updater/](https://git-updater.com/git-updater/) )  to update Paytabs plugin automatically, which in turns would help everyone keeps the environment safe and up-to-date.

```
<?php

/**
 * @package PayTabs_PayPage
 */

/**
 * Plugin Name:   PayTabs - WooCommerce Payment Gateway
 * Plugin URI:    https://paytabs.com/
 * Description:   PayTabs is a <strong>3rd party payment gateway</strong>. Ideal payment solutions for your internet business.
 * Version:       4.11.2
 * Requires PHP:  7.0
 * Author:        PayTabs
 * Author URI:    w.kammoun@paytabs.com
 * Revision Date: 21/April/2022
 */
```

on a side note,  I don't think the Author URI: is a valid syntax.  **mailto:**w.kammoun@paytabs.com might be

**Comment by fabricelaborie** [comment]
Hi Paytabs team,
Adding this header would make life easier for your customer and keep us safe by facilitating quick / automated upgrades.
Can you add  the "GitHub Plugin URI:"  header ?

**Comment by wajihkm** [comment]
Hi @fabricelaborie 
Thanks for the notes.
Kindly check the latest release 5.6.2
