### ISSUE TITLE
AMEX or Installment payment method not shown in USD store currency

### ISSUE THREAD

**Issue by nobel0** [paytabscom/paytabs-woocommerce#40]
Hello Dears,
Good morning/evening

I have been emailing AMEX and PayTabs team for the problem i am facing.
Let me describe a bit: My store is in USD currency, on the checkout i cannot see anything other than the credit cards payment method.
Hint: PayTabs confirmed along with AMEX that it is okay to receive AMEX payments with USD currency to my account in PayTabs, it will be converted afterthen to SAR automatically. So this feature is doable.

**Can you please add those payment methods for the store owners who runs their store in USD currency?**

Note: If i switched my store to SAR, these payment methods will be ok and shown in the checkout, unlike if USD store.

Thanks
Best Regards

**Comment by nobel0** [comment]
@paytabscom any help please ?
Thanks

**Comment by wajihkm** [comment]
Hi @nobel0 

AMEX enabled for AED & SAR only in our plugins.

**Comment by nobel0** [comment]
@wajihkm Thanks, is it possible to add it if i hired a developer? As i spoke with the PayTabs team, they said it should works but i may need a developer to do that maybe..
Thanks

**Comment by wajihkm** [comment]
Hi @nobel0 

Kindly install the latest version (4.14.2), we have added USD as accepted currency to AMEX.

Regards,
Wajih
