### ISSUE TITLE
'phone_number' post variable not found

### ISSUE THREAD

**Issue by modymok** [paytabscom/paytabs-woocommerce#7]
on check out pages i get this error 
**'phone_number' post variable not found**

**Comment by wajihkm** [comment]
Hi @modymok,
Which plugin release you are using?
If possible also to list the current wp & woocommerce version you are using.
Thanks

**Comment by Jazzykhan** [comment]
I am getting cc_phone_variable not found i have latest plugin and latest woo commerce.

**Comment by wajihkm** [comment]
Hi @Jazzykhan ,
Sorry to hear that.
Could you please mention the website URL?
Could you also please check the paytabs' log in the file "debug_paytabs.log" ?

for any further help you can contact:
customercare@paytabs.com
Thanks
