### ISSUE TITLE
Woocommerce only shows the Credit Card method even if others are enabled

### ISSUE THREAD

**Issue by elqusiry** [paytabscom/paytabs-woocommerce#9]
Hello,

I'm facing an issue on a client's website where no matter how many Paytabs Payment Methods I enable only the Credit Card method is available to the users. Other non-paytabs payment methods are working fine.

WP Version: 5.5.1

**Comment by wajihkm** [comment]
Hi @elqusiry 

What is the used currency?
Thanks

**Comment by elqusiry** [comment]
Hi @wajihkm 

It's Saudi Ryials

**Comment by wajihkm** [comment]
Hi @elqusiry 

for SAR, the available payment methods are:
STCPay, ApplePay, MADA, SADAD, AMEX and CreditCard

if you tried the above payment methods and got the same issue, That means there is a problem with your currency code.

Thanks
